---
title: "Traffic_violators"
author: "Violators"
date: "`r format(Sys.time(), '%d %B, %Y')`" 
output: 
  html_document:
    
    theme: flatly
    toc: TRUE
    toc_float: TRUE
    code_download: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, cache = F}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  warning= FALSE,
  message= FALSE)
```

##Loading package
```{r}
library(tidyverse)

```


##Reading two datasets
```{r}
#To make sure the working directory of the data set
getwd()
#Importing csv files
traffic <- read_csv("Traffic.csv")
weather <- read_csv("weather.csv")
```

```{r}
#For outline look of the dataset and variables of traffic dataset.
glimpse(traffic)

#Data set contains lot of column names which have space which can create complexity in manipulation and visualization so renaming the data set traffic columns using rename function as part of data preparation

traffic <-  rename(traffic, Date = 'Date Of Stop', time_of_stop = 'Time Of Stop', personal_injury = 'Personal Injury', property_damage = 'Property Damage', commercial_license = 'Commercial License', Commercial_Vehicle = 'Commercial Vehicle', Work_Zone ='Work Zone', Search_Conducted = 'Search Conducted', Search_Disposition = 'Search Disposition', Search_Outcome = 'Search Outcome', Search_Reason = 'Search Reason', Search_Reason_Stop = 'Search Reason For Stop', Search_Type ='Search Type', Search_Arrest_r = 'Search Arrest Reason', Violation_Type ='Violation Type', Contributed_Accident='Contributed To Accident', Driver_City = 'Driver City', Driver_State = 'Driver State', DL_State = 'DL State', Arrest_Type = 'Arrest Type')

#For outline look of the dataset and variables of the weather dataset.
glimpse(weather)

#Dataset column precipitation had spacing issue so renaming the column using rename function as part of data preparation.
weather <- rename(weather, precipitation = 'Precipitation (in)')
```

#Combing Two datasets data.
```{r}
#Using inner join combing two datasets based on Date. 
trafficfull <- traffic %>%  inner_join(weather, by = "Date")

#Exporting the combined dataset as CSV file.
write_csv(trafficfull, 'Dataset.csv')
t <- read_csv('Dataset.csv')
```


#Exploration 
```{r}
glimpse(trafficfull)
```

#refining Dataset
```{r}

tf <- sample_n(trafficfull, 800000)
tf <- tf %>% separate(Date,into = c("month","day","year"))
glimpse(tf)

write_csv(tf, 'S.csv')
```

#Question 1


```{r}

# Statistics

t1<- tf %>% group_by(Race) %>% summarise(count = n())

t2 <- tf %>%  filter(Search_Reason == 'Probable cause' | Search_Reason == 'Incident to Arrest' ) %>% select(Race) %>%  group_by(Race) %>% summarise(Search = n()) 

t3 <- tf %>% filter(Alcohol == 'Yes') %>% select(Race) %>% group_by(Race) %>% summarise(Alcohol= n())

 t4 <- tf%>% filter(Violation_Type == "Warning") %>% select(Race) %>% group_by(Race) %>% summarise(Warning = n())

t5 <- tf %>% filter(Violation_Type == "Citation") %>% select(Race) %>% group_by(Race) %>% summarise(citation = n())

t6 <- tf %>% filter(Accident == "Yes") %>% select(Race) %>% group_by(Race) %>% summarise(accident = n())

q1 <- t1 %>% inner_join(t2,by = 'Race') %>% inner_join(t3, by = 'Race') %>%  inner_join(t4, by = 'Race') %>% inner_join(t5, by = 'Race') %>% inner_join(t6, by = 'Race') 


#Visualization

ggplot(q1)+ geom_point(mapping = aes(x=Search, y = accident), shape = 8, size = 2) + geom_point(mapping =  aes(x = Search, y =citation,  color = Alcohol ), shape = 15,  size = 3)+geom_point(mapping =  aes(x = Search, y =Warning),shape = 17, size = 3) + facet_grid(~ Race) 


```

#Question 2

```{r}
#statistics

glimpse(tf)

tf  %>%  group_by(Gender) %>% summarise(Count =n())
t1 <- tf %>% filter(Accident == 'Yes') %>% select(Gender) %>%  group_by(Gender) %>% summarise(accident =n()) 
t2 <- tf %>% filter(Belts == 'No') %>% select(Gender) %>%  group_by(Gender) %>% summarise(belts =n()) 
t3 <- tf %>% filter(property_damage == 'Yes') %>% select(Gender) %>%  group_by(Gender) %>% summarise(property =n()) 
t4 <- tf %>% filter(Fatal == 'Yes') %>% select(Gender) %>%  group_by(Gender) %>% summarise(fatal =n()) 
t5 <- tf %>% filter(Alcohol == 'Yes') %>% select(Gender) %>%  group_by(Gender) %>% summarise(alcohol =n()) 

q2 <- t1 %>% inner_join(t2,by = 'Gender') %>% inner_join(t3, by = 'Gender') %>%  inner_join(t4, by = 'Gender') %>% inner_join(t5, by = 'Gender')

view(q2)

#Visualization
ggplot(q2)+geom_point(mapping = aes(x = belts, y = accident ), shape = 18 ,size =3 ,color ='#FC4E07') + geom_point(mapping = aes(x = belts, y = property), shape =17, size =2) + geom_point(mapping = aes(x = belts, y = fatal), size =2)+  geom_point(mapping = aes(x = belts, y = alcohol), shape = 15, size = 2.5, color ='#0000FF' )+facet_wrap(~Gender)

```

#Question 3

```{r}
#statics
glimpse(tf)


tf %>% filter(Accident == 'Yes') %>% group_by(month, year) %>% summarise(Count =n())  %>% arrange(desc(Count))
tf %>% filter(Accident == 'Yes') %>% group_by(month, year) %>% summarise(Count =n())  %>% arrange(Count)
tf %>% filter(Accident == 'Yes') %>% group_by(month) %>% summarise(Count =n())  %>% arrange(Count)
tf %>% filter(Accident == 'Yes') %>% group_by(month) %>% summarise(Count =n())  %>% arrange(desc(Count))
tf %>% filter(Accident == 'Yes') %>% group_by(year) %>% summarise(Count =n())  %>% arrange(Count)
tf %>% filter(Accident == 'Yes') %>% group_by(year) %>% summarise(Count =n())  %>% arrange(desc(Count))

#Visualization

tf %>% filter(Accident == 'Yes') %>% ggplot(aes(x=year,color = year, fill = year))+geom_bar() + facet_wrap(~month)
tf %>% filter(Accident == 'Yes') %>% ggplot(aes(x=year, color = year, fill = year))+geom_bar()
tf %>% filter(Accident == 'Yes') %>% ggplot(aes(x=month, color = year, fill = year))+geom_bar()

```

#Question 4

```{r}
glimpse(tf)

#temperature effect.

tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )   %>%  summarise(min(Avg_temp))

tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=10 & 1 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=20 & 11 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=30 & 21 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=40 & 31 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=50 & 41 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=60 & 51 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=70 & 61 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=80 & 71 <= Avg_temp ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_temp )  %>% filter(Avg_temp <=90 & 81 <= Avg_temp ) %>%  summarise(count = n())


#Humidity effect.

tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )   %>%  summarise(max(Avg_hum))
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=10 & 1 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=20 & 11 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=30 & 21 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=40 & 31 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=50 & 41 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=60 & 51 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=70 & 61 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=80 & 71 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=90 & 81 <= Avg_hum ) %>%  summarise(count = n())
tf %>%  filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% select(  Avg_hum )  %>% filter(Avg_hum <=100 & 91 <= Avg_hum ) %>%  summarise(count = n())

#Visualization
tf %>% filter(Accident == 'Yes' | personal_injury == 'Yes' |property_damage == 'Yes' | Fatal == 'Yes') %>% ggplot(aes(x=Avg_temp , fill = "Temperature") )+geom_bar() + geom_bar(mapping =  aes(x=Avg_hum, fill = "Humidity" ))

```

